version: '3'

services:  

  redis:
    image: redis:latest
    hostname: redis

  web:
    image: brian32768/pylette:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: scripts/run_server.sh
    user: app
    volumes:
      - .:/srv/pylette
    ports:
      - "5100:5000"
    links:
      - redis

  worker:
    image: brian32768/pylette:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: scripts/run_celery.sh
    user: app
    volumes:
      - .:/srv/pylette
    links:
      - redis
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
